apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: guom101ms-go 
  janus-idp.io/tekton: guom101ms-go
  backstage.io/kubernetes-id: guom101ms-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: guom101ms-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  